### ISSUE TITLE
i have a bit problem

### ISSUE THREAD

**Issue by anbinh2504** [aws-samples/amazon-ecs-agent-connection-monitoring#4]
Dear Sir 
My name is Binh ,i am a university student in Vietnam, recently I received this project topic my initial steps went smoothly according to your instructions until I created the CloudFormation stack then I encountered this error, If you have time, please guide me how to fix it, sorry for bothering you.
Best regards.
![Untitled](https://github.com/aws-samples/amazon-ecs-agent-connection-monitoring/assets/153150799/f340561a-339a-42f3-aa44-1a08f7cff339)

**Comment by henriquesantanati** [comment]
Hello @PhamNguyenAnBinh , 

I just tried from my side using the `packaged-template.yaml` generated by the command `aws cloudformation package` and it worked as expected. 

Please check the step 3 [here](https://github.com/aws-samples/amazon-ecs-agent-connection-monitoring?tab=readme-ov-file#step-by-step) where you can see the full package command and how to use the file output generated to create the stack.

Double checking the [blog post](https://aws.amazon.com/blogs/containers/monitoring-the-amazon-ecs-agent/) I was able to see that we are misleading the reader informing that they should use the `ecs-agent-monitoring.yaml` from step 1 which is wrong. 

I'll ask for update the blog post with the correct information. Thank you for raising this. 

Let me know if this helps you. Otherwise, please provide all the steps that you are doing with more details and we should be able to reproduce the same issue from our side. 

I'm marking this as resolved, feel free to reopen it if you still have issues.

**Comment by anbinh2504** [comment]
I have implemented the solution, thank you for taking the time to answer my problem
